version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: wednesday
    time: "12:00"
  open-pull-requests-limit: 10
  groups:
    eslint:
      patterns:
      - "eslint*"
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    # Check for updates to GitHub Actions every week
    interval: weekly
    day: wednesday
    time: "12:00"
