name: Dependabot auto-approve
on: pull_request

permissions:
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Approve a PR
        if: ${{
            steps.metadata.outputs.dependency-type == 'direct:development'
              || steps.metadata.outputs.update-type == 'version-update:semver-patch'
              || steps.dependabot-metadata.outputs.dependency-group == 'test-dependencies'
              || steps.dependabot-metadata.outputs.dependency-group == 'maven-plugins'
          }}
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
